import "@quasar/extras/material-icons/material-icons.css";
import {
  QBtn,
  Quasar,
  QDialog,
  QImg,
  QBtnDropdown,
  QItem,
  QList,
  QItemSection,
  QItemLabel,
  QInput,
  QIcon,
  QSelect,
  QCard,
  QRadio,
  QSkeleton,
  QRating,
  QTabs,
  QTab,
  QForm,
  QMarkupTable,
  QSlider,
  Loading,
  QExpansionItem,
  QRange,
  QCheckbox,
  QFile,
} from "quasar";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Quasar, {
    plugins: { Loading },
    components: {
      QCheckbox,
      QRange,
      QExpansionItem,
      QBtn,
      QDialog,
      QImg,
      QBtnDropdown,
      QItem,
      QList,
      QItemSection,
      QItemLabel,
      QInput,
      QIcon,
      QSelect,
      QCard,
      QRadio,
      QSkeleton,
      QRating,
      QTabs,
      QTab,
      QForm,
      QMarkupTable,
      QSlider,
      QFile,
    },
  });
});
