name: Dockerize Telegram Bot

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push test-bot
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: shukhratutaboev/test-bot:latest
          no-cache: true

  deploy:    
    runs-on: self-hosted
    needs: dockerize
    steps:
      - name: deploy telegram bot
      - run: cs ../../../..
      - run: docker rm --force /test-bot && docker image prune -a && docker pull shukhratutaboev/test-bot:latest && docker compose build --no-cache test-bot && docker-compose up -d --no-deps test-bot
